// Define all action types

export const SET_WRITE_PERMISSION = "SET_WRITE_PERMISSION";
export const DISPLAY_LOADER = "DISPLAY_LOADER";
export const DISPLAY_PLAYER = "DISPLAY_PLAYER";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const SET_SELECTED_FILES = "SET_SELECTED_FILES";
export const SET_SELECT_FILE = "SET_SELECT_FILE";